"""
pipeline/load_agents.py

Reads mirofish/config/nepse_agents.json and registers all 1000 NEPSE agents
into a MiroFish simulation by building an ontology-aware simulation_requirement.

In MiroFish's architecture, agents are NOT pre-registered via a direct API —
they are generated by LLM from the entity types declared in the ontology.
This module formats our 6 agent groups as entity type descriptions that
MiroFish's ontology generator and profile generator use to create
OASIS-format agent profiles.

Usage:
    python pipeline/load_agents.py                   # summary only
    python pipeline/load_agents.py --sim-id SIM_XYZ  # validate against live sim
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent

AGENTS_CONFIG = _ROOT / "mirofish" / "config" / "nepse_agents.json"
MIROFISH_BASE = "http://localhost:5001"


def load_agent_config() -> dict:
    """Load and return the nepse_agents.json config."""
    if not AGENTS_CONFIG.exists():
        raise FileNotFoundError(f"Agent config not found: {AGENTS_CONFIG}")
    return json.loads(AGENTS_CONFIG.read_text(encoding="utf-8"))


def build_simulation_requirement(config: dict) -> str:
    """
    Convert the agent config into a rich simulation_requirement string.

    This text is passed to MiroFish's ontology generation endpoint alongside
    the seed document. It instructs the LLM on what kinds of agents to create
    and how they should behave.
    """
    groups = config.get("agent_groups", [])
    total  = sum(g["count"] for g in groups)

    lines = [
        "NEPAL STOCK EXCHANGE (NEPSE) MULTI-AGENT MARKET SIMULATION",
        "=" * 60,
        "",
        f"Simulate {total} investors across 6 distinct groups participating in Nepal's",
        "stock market over 3 trading days. Each group has different information",
        "sources, decision frameworks, risk tolerance, and social media behaviour.",
        "",
        "INVESTOR GROUPS AND THEIR BEHAVIOURS:",
        "",
    ]

    for g in groups:
        lines += [
            f"## {g['type'].replace('_', ' ').title()} ({g['count']} agents, prefix: {g['name_prefix']})",
            f"Risk tolerance: {g['risk_tolerance']} (0=very low, 1=very high)",
            f"Memory weight: {g['memory_weight']} (how much past events influence them)",
            f"Preferred sectors: {', '.join(g['preferred_sectors'])}",
            f"Decision framework: {g['decision_framework']}",
            f"Social behaviour: {g['social_behavior']}",
            f"Trigger events: {'; '.join(g['trigger_events'][:3])}",
            f"Nepal context: {g.get('nepal_context', '')}",
            "",
        ]

    lines += [
        "SIMULATION QUESTION:",
        "Based on today's NEPSE seed data provided in the uploaded document,",
        "simulate how these 6 investor groups interact across StockTalk Nepal",
        "(Twitter-like) and r/NepseInvestors (Reddit-like) platforms over 3 trading days.",
        "",
        "Track: sentiment shifts, viral posts, sector-specific opinions,",
        "cross-platform dynamics, and the evolution of market consensus.",
        "",
        "Output: Round-by-round sentiment, top influential agents, key themes debated,",
        "and final directional consensus (BULLISH / BEARISH / NEUTRAL).",
    ]

    return "\n".join(lines)


def get_agent_summary(config: dict) -> dict:
    """Returns a summary dict for printing."""
    groups = config.get("agent_groups", [])
    return {
        "total_agents":  sum(g["count"] for g in groups),
        "groups":        len(groups),
        "breakdown":     {g["type"]: g["count"] for g in groups},
        "total_sectors_covered": sorted({s for g in groups for s in g["preferred_sectors"]}),
    }


def validate_against_sim(sim_id: str, base_url: str = MIROFISH_BASE) -> dict:
    """
    Check a running MiroFish simulation's profiles against our agent config.
    Returns comparison dict.
    """
    import requests

    config  = load_agent_config()
    summary = get_agent_summary(config)

    try:
        r_reddit  = requests.get(f"{base_url}/simulation/{sim_id}/profiles",
                                  params={"platform": "reddit"}, timeout=15)
        r_twitter = requests.get(f"{base_url}/simulation/{sim_id}/profiles",
                                  params={"platform": "twitter"}, timeout=15)

        reddit_profiles  = (r_reddit.json().get("data") or []) if r_reddit.ok else []
        twitter_profiles = (r_twitter.json().get("data") or []) if r_twitter.ok else []

        return {
            "sim_id":                 sim_id,
            "expected_agent_groups":  summary["groups"],
            "expected_total_agents":  summary["total_agents"],
            "reddit_profiles_found":  len(reddit_profiles),
            "twitter_profiles_found": len(twitter_profiles),
            "status": "ok" if (reddit_profiles or twitter_profiles) else "no_profiles",
        }
    except Exception as exc:
        return {"error": str(exc), "sim_id": sim_id}


# ── CLI ────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse
    sys.stdout = __import__("io").TextIOWrapper(
        sys.stdout.buffer, encoding="utf-8", errors="replace"
    )

    ap = argparse.ArgumentParser(description="Show NEPSE agent config summary")
    ap.add_argument("--sim-id", default=None,
                    help="Validate profiles in a live MiroFish simulation")
    ap.add_argument("--show-requirement", action="store_true",
                    help="Print the full simulation_requirement text")
    args = ap.parse_args()

    GREEN = "\033[92m"; CYAN = "\033[96m"; BOLD = "\033[1m"; RESET = "\033[0m"

    config  = load_agent_config()
    summary = get_agent_summary(config)
    req_txt = build_simulation_requirement(config)

    print(f"\n{BOLD}NEPSE Agent Configuration Summary{RESET}")
    print("=" * 50)
    print(f"  Total agents  : {BOLD}{summary['total_agents']}{RESET}")
    print(f"  Agent groups  : {summary['groups']}")
    print(f"  Sectors covered: {', '.join(summary['total_sectors_covered'])}")
    print()
    print(f"  {CYAN}Breakdown by type:{RESET}")
    for agent_type, count in summary["breakdown"].items():
        print(f"    {agent_type:<30} {count:>4} agents")

    if args.show_requirement:
        print(f"\n{CYAN}Simulation Requirement Text:{RESET}")
        print("-" * 50)
        print(req_txt)

    if args.sim_id:
        print(f"\n{CYAN}Validating against simulation {args.sim_id}...{RESET}")
        result = validate_against_sim(args.sim_id)
        for k, v in result.items():
            print(f"  {k}: {v}")

    print(f"\n{GREEN}Agent config loaded successfully.{RESET}")
    print(f"  Config path: {AGENTS_CONFIG}")
    print()
