"""
paper_trading/weekly_review.py
Automated weekly paper-trading review generated by Claude every Friday 18:00 NST.
Saves to: data/processed/paper_trading/weekly_review_week{N}.md

Schedule:
  Friday 12:15 UTC = Friday 18:00 NST (UTC+5:45)

Run:
  python -m paper_trading.weekly_review              # start scheduler
  python -m paper_trading.weekly_review --run-now    # generate immediately
  python -m paper_trading.weekly_review --week-num 3 # generate for week 3
"""

from __future__ import annotations

import glob
import json
import logging
import os
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Nepal Standard Time offset (UTC+5:45)
# ---------------------------------------------------------------------------
NST_OFFSET_HOURS = 5
NST_OFFSET_MINUTES = 45


def _nst_now() -> datetime:
    """Return current time as NST (UTC+5:45)."""
    from datetime import timezone, timedelta as _td
    nst = timezone(_td(hours=NST_OFFSET_HOURS, minutes=NST_OFFSET_MINUTES))
    return datetime.now(tz=nst)


# ---------------------------------------------------------------------------
# Prompt template
# ---------------------------------------------------------------------------

WEEKLY_REVIEW_PROMPT = """You are the lead quantitative analyst for a NEPSE (Nepal Stock Exchange) algorithmic trading system called MiroFish.
Write a comprehensive weekly paper-trading review for Week {week_num} based on the data provided below.
The report must be professional, data-driven, and actionable.

## DATA FOR ANALYSIS

```json
{data_json}
```

---

## REPORT STRUCTURE

Write the full Markdown report. Use the exact section headings below and include all requested content.

### 1. Executive Summary
One paragraph (4–6 sentences) summarising the week's performance, key events, signal quality, and the single most important takeaway for strategy improvement.

### 2. Performance vs NEPSE Index
Compare paper portfolio return this week vs NEPSE index movement.
- Week return: {week_return_pct:.2f}%
- NEPSE return this week: {nepse_return_pct}
- Cumulative return since session start: {cumulative_return_pct:.2f}%
- Alpha generated: {alpha_pct}
Discuss whether outperformance/underperformance is explained by regime or signal quality.

### 3. Best Trades (Top 3)
List the 3 best closed trades this week with:
- Symbol, entry/exit price, P&L%, holding days
- Which signal component drove the entry (MiroFish score, RSI, volume)
- One-sentence rationale for why this trade worked

### 4. Worst Trades (Top 3)
List the 3 worst closed/open trades this week with:
- Symbol, entry price, current/exit price, P&L%, holding days
- Root cause analysis (wrong regime call, stop-loss too wide/tight, signal noise)
- Specific lesson to apply going forward

### 5. Signal Accuracy Analysis
Analyse signal accuracy across all evaluation windows:
- 1-day accuracy: {acc_1d}
- 3-day accuracy: {acc_3d}
- 5-day accuracy: {acc_5d}
- Last 10 signals: {acc_last10}
- Accuracy trend: {acc_trend}
- Watchlist accuracy (5d): {acc_watchlist_5d}
Identify any regime-specific accuracy patterns. Flag if accuracy dropped below 50%.

### 6. MiroFish Quality Assessment
Evaluate MiroFish model performance this week:
- Did MiroFish bull/bear score align with actual NEPSE direction?
- Score range observed this week: {mf_score_min} to {mf_score_max}
- Any divergence between MiroFish score and market outcome?
- Recommendation: continue/retune/pause MiroFish signal weight

### 7. Risk Management Assessment
Review position sizing, stop-loss adherence, and capital allocation:
- Positions stopped out this week: {stops_hit}
- Targets hit: {targets_hit}
- Maximum drawdown this week: {max_drawdown_pct}%
- Cash utilisation: {cash_utilisation_pct}%
- Were position sizes appropriate given regime confidence?

### 8. Market Regime Assessment
Analyse current and recent regime calls:
- Current regime: {current_regime}
- Regime changes this week: {regime_changes}
- Was the detected regime consistent with NEPSE price action?
- Regime confidence and its effect on position sizing

### 9. Strategy Adjustments for Next Week
Provide 3–5 specific, actionable adjustments based on this week's data.
Each adjustment must be:
- Specific (what to change, not vague advice)
- Measurable (how to know if it worked)
- Linked to evidence from this week's data

### 10. Go-Live Progress
Track progress toward live trading criteria:
- Trading days completed: {trading_days_elapsed}/20
- Signal accuracy criterion (≥55% at 3d window): {acc_criterion_status}
- Maximum drawdown criterion (≤8%): {drawdown_criterion_status}
- Win rate criterion (≥45%): {win_rate_criterion_status}
- Regime detection criterion (≥3 correct calls): {regime_criterion_status}
- Estimated weeks to go-live readiness: {weeks_to_live}
- Overall assessment: READY / NOT_READY / ON_TRACK

---

Write the report now. Be precise with numbers from the data. Use Markdown formatting.
Avoid generic financial boilerplate — every statement must be grounded in the data provided.
"""


# ---------------------------------------------------------------------------
# Data collection helper
# ---------------------------------------------------------------------------

@dataclass
class WeekData:
    """Container for all data collected for the weekly review."""

    session_id: str
    week_num: int
    week_start: date
    week_end: date

    # Portfolio
    portfolio_value_start: float = 0.0
    portfolio_value_end: float = 0.0
    starting_capital: float = 1_000_000.0
    cash_end: float = 0.0

    # Trades
    closed_trades: list[dict] = field(default_factory=list)
    open_positions: list[dict] = field(default_factory=list)

    # Regime / signal
    regime_history: list[dict] = field(default_factory=list)
    mirofish_scores: list[float] = field(default_factory=list)

    # Accuracy
    accuracy_report: dict = field(default_factory=dict)

    # NEPSE index
    nepse_start: Optional[float] = None
    nepse_end: Optional[float] = None

    # Cycle logs
    cycle_logs: list[dict] = field(default_factory=list)

    # ── Computed properties ─────────────────────────────────────────────────

    @property
    def week_return_pct(self) -> float:
        if self.portfolio_value_start <= 0:
            return 0.0
        return (self.portfolio_value_end / self.portfolio_value_start - 1) * 100

    @property
    def cumulative_return_pct(self) -> float:
        if self.starting_capital <= 0:
            return 0.0
        return (self.portfolio_value_end / self.starting_capital - 1) * 100

    @property
    def nepse_week_return_pct(self) -> Optional[float]:
        if self.nepse_start and self.nepse_end and self.nepse_start > 0:
            return round((self.nepse_end / self.nepse_start - 1) * 100, 2)
        return None

    @property
    def alpha_pct(self) -> Optional[float]:
        nepse = self.nepse_week_return_pct
        if nepse is None:
            return None
        return round(self.week_return_pct - nepse, 2)

    @property
    def win_rate_pct(self) -> Optional[float]:
        if not self.closed_trades:
            return None
        wins = sum(1 for t in self.closed_trades if t.get("pnl_pct", 0) > 0)
        return round(wins / len(self.closed_trades) * 100, 1)

    @property
    def max_drawdown_pct(self) -> float:
        """Intra-week max drawdown from equity snapshots."""
        values = [s.get("value", 0) for s in self._week_snapshots if s.get("value")]
        if not values:
            return 0.0
        peak = values[0]
        max_dd = 0.0
        for v in values:
            if v > peak:
                peak = v
            dd = (peak - v) / peak * 100 if peak > 0 else 0.0
            max_dd = max(max_dd, dd)
        return round(max_dd, 2)

    @property
    def cash_utilisation_pct(self) -> float:
        if self.portfolio_value_end <= 0:
            return 0.0
        invested = self.portfolio_value_end - self.cash_end
        return round(invested / self.portfolio_value_end * 100, 1)

    # internal shorthand used by max_drawdown_pct
    _week_snapshots: list[dict] = field(default_factory=list, repr=False)


# ---------------------------------------------------------------------------
# WeeklyReviewer
# ---------------------------------------------------------------------------

class WeeklyReviewer:
    """
    Generates an automated weekly review of paper trading performance.
    Uses Claude API when available; falls back to template-based report.
    """

    OUTPUT_DIR = Path("data/processed/paper_trading")

    def __init__(self, session_id: str, data_dir: str = "data/paper_trading"):
        self.session_id = session_id
        self._base = Path(data_dir) / session_id
        self._base.mkdir(parents=True, exist_ok=True)
        self.OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # ── Public API ───────────────────────────────────────────────────────────

    def collect_week_data(self) -> WeekData:
        """Gather all stats for the past week from disk files."""
        today = date.today()
        # Week ending today (Mon=0 … Sun=6; NEPSE: Sun–Thu)
        week_end   = today
        week_start = today - timedelta(days=6)
        week_num   = self._compute_week_num()

        wd = WeekData(
            session_id=self.session_id,
            week_num=week_num,
            week_start=week_start,
            week_end=week_end,
        )

        self._load_state(wd)
        self._load_snapshots(wd)
        self._load_trade_log(wd)
        self._load_accuracy(wd)
        self._load_cycle_logs(wd)
        self._load_nepse_index(wd)

        return wd

    def generate_review(self, week_num: int) -> str:
        """
        Generate the weekly review markdown.
        Uses Claude claude-sonnet-4-5 when ANTHROPIC_API_KEY is set; otherwise falls back to
        a structured template-based report.
        """
        wd = self.collect_week_data()
        wd.week_num = week_num

        api_key = os.getenv("LLM_API_KEY", "")
        if api_key and not api_key.startswith("your_"):
            return self._generate_with_claude(wd, api_key)
        else:
            logger.warning(
                "LLM_API_KEY not set — generating template-based report for week %d", week_num
            )
            return self._generate_template_report(wd)

    def save_review(self, content: str, week_num: int) -> Path:
        """Save the markdown review to data/processed/paper_trading/."""
        out_path = self.OUTPUT_DIR / f"weekly_review_week{week_num}.md"
        out_path.write_text(content, encoding="utf-8")
        logger.info("Weekly review saved to %s", out_path)
        return out_path

    def run_weekly_review(self) -> dict:
        """
        Full orchestration: collect → generate → save → send Telegram.
        Returns a result dict.
        """
        logger.info("=== Weekly Review: %s ===", _nst_now().strftime("%Y-%m-%d %H:%M NST"))
        week_num = self._compute_week_num()

        try:
            content = self.generate_review(week_num)
        except Exception as exc:
            logger.error("Review generation failed: %s", exc)
            return {"status": "error", "error": str(exc)}

        out_path = self.save_review(content, week_num)

        # Send Telegram summary
        summary = self._extract_telegram_summary(content, week_num)
        self._send_telegram(summary)

        return {
            "status": "ok",
            "week_num": week_num,
            "path": str(out_path),
            "chars": len(content),
            "generated_at": _nst_now().isoformat(),
        }

    # ── Data loading ─────────────────────────────────────────────────────────

    def _load_state(self, wd: WeekData) -> None:
        """Load current state.json."""
        path = self._base / "state.json"
        if not path.exists():
            return
        try:
            with open(path, encoding="utf-8") as fh:
                state = json.load(fh)
            wd.starting_capital = float(state.get("starting_capital", 1_000_000))
            wd.cash_end         = float(state.get("capital", 0))
            wd.open_positions   = list(state.get("positions", {}).values())
        except Exception as exc:
            logger.warning("State load failed: %s", exc)

    def _load_snapshots(self, wd: WeekData) -> None:
        """Load snapshot files for the week and build equity history."""
        pattern = str(self._base / "snapshot_*.json")
        all_snaps = sorted(glob.glob(pattern))

        week_snaps: list[dict] = []
        all_pts: list[dict] = []

        for path in all_snaps:
            try:
                with open(path, encoding="utf-8") as fh:
                    snap = json.load(fh)
                snap_date_str = snap.get("date") or snap.get("snapshot_date", "")
                pv = snap.get("portfolio_value", 0.0)
                all_pts.append({"date": snap_date_str, "value": float(pv)})

                try:
                    snap_date = date.fromisoformat(str(snap_date_str))
                    if wd.week_start <= snap_date <= wd.week_end:
                        week_snaps.append({"date": snap_date_str, "value": float(pv)})
                except ValueError:
                    pass

                # Regime history
                if snap.get("regime"):
                    wd.regime_history.append({
                        "date":           snap_date_str,
                        "regime":         snap.get("regime"),
                        "mirofish_score": snap.get("mirofish_score"),
                    })
                if snap.get("mirofish_score") is not None:
                    wd.mirofish_scores.append(float(snap["mirofish_score"]))

            except Exception as exc:
                logger.debug("Snapshot load error for %s: %s", path, exc)

        wd._week_snapshots = week_snaps

        # Portfolio value at start and end of week
        if all_pts:
            # Start of week: last snapshot before or on week_start
            before_week = [p for p in all_pts if p["date"] <= str(wd.week_start)]
            wd.portfolio_value_start = (
                float(before_week[-1]["value"]) if before_week else float(all_pts[0]["value"])
            )
            wd.portfolio_value_end = float(all_pts[-1]["value"])

    def _load_trade_log(self, wd: WeekData) -> None:
        """Load closed trade log for the session."""
        path = self._base / "state.json"
        if not path.exists():
            return
        try:
            with open(path, encoding="utf-8") as fh:
                state = json.load(fh)
            trade_log = state.get("trade_log", [])
            # Filter to trades closed this week
            week_trades = []
            for t in trade_log:
                exit_date_str = t.get("exit_date", "")
                try:
                    exit_d = date.fromisoformat(str(exit_date_str))
                    if wd.week_start <= exit_d <= wd.week_end:
                        week_trades.append(t)
                except ValueError:
                    pass
            wd.closed_trades = week_trades
        except Exception as exc:
            logger.warning("Trade log load failed: %s", exc)

    def _load_accuracy(self, wd: WeekData) -> None:
        """Load accuracy_report.json."""
        path = self._base / "accuracy_report.json"
        if path.exists():
            try:
                with open(path, encoding="utf-8") as fh:
                    wd.accuracy_report = json.load(fh)
            except Exception as exc:
                logger.warning("Accuracy report load failed: %s", exc)

    def _load_cycle_logs(self, wd: WeekData) -> None:
        """Load daily cycle logs for the week."""
        pattern = str(self._base / "cycle_*.json")
        files = sorted(glob.glob(pattern), reverse=True)[:7]
        for path in files:
            try:
                with open(path, encoding="utf-8") as fh:
                    log = json.load(fh)
                log_date_str = log.get("date", "")
                try:
                    log_date = date.fromisoformat(str(log_date_str))
                    if wd.week_start <= log_date <= wd.week_end:
                        wd.cycle_logs.append(log)
                except ValueError:
                    pass
            except Exception as exc:
                logger.debug("Cycle log load error for %s: %s", path, exc)

    def _load_nepse_index(self, wd: WeekData) -> None:
        """Attempt to load NEPSE index values for the week."""
        try:
            from db.loader import get_market_snapshot  # type: ignore[import]
            snap_start = get_market_snapshot(str(wd.week_start))
            snap_end   = get_market_snapshot(str(wd.week_end))
            if snap_start:
                wd.nepse_start = snap_start.get("nepse_index") or snap_start.get("nepse_close")
            if snap_end:
                wd.nepse_end = snap_end.get("nepse_index") or snap_end.get("nepse_close")
        except Exception as exc:
            logger.debug("NEPSE index load failed: %s", exc)

    # ── Claude generation ────────────────────────────────────────────────────

    def _generate_with_claude(self, wd: WeekData, api_key: str) -> str:
        """Call Groq (llama-3.3-70b-versatile) to write the weekly review."""
        from openai import OpenAI

        client = OpenAI(
            api_key=api_key,
            base_url=os.getenv("LLM_BASE_URL", "https://api.groq.com/openai/v1"),
        )

        data_dict = self._wd_to_dict(wd)
        prompt = self._build_prompt(wd, data_dict)
        model = os.getenv("LLM_MODEL_NAME", "llama-3.3-70b-versatile")

        logger.info("Calling Groq %s for week %d review…", model, wd.week_num)
        try:
            response = client.chat.completions.create(
                model=model,
                max_tokens=4096,
                messages=[{"role": "user", "content": prompt}],
            )
            content = response.choices[0].message.content
            header = self._build_report_header(wd)
            return header + "\n\n" + content
        except Exception as exc:
            logger.error("Groq API call failed: %s — falling back to template", exc)
            return self._generate_template_report(wd)

    def _build_prompt(self, wd: WeekData, data_dict: dict) -> str:
        """Format the WEEKLY_REVIEW_PROMPT with week data."""
        acc = wd.accuracy_report

        def _fmt_pct(v: Optional[float]) -> str:
            if v is None:
                return "N/A"
            return f"{v:.1f}%"

        # Stops hit and targets hit from cycle logs
        stops_hit   = sum(
            step.get("exits", 0)
            for log in wd.cycle_logs
            for step in log.get("steps", [])
            if step.get("name") == "check_exits"
        )
        targets_hit = 0  # cycle log doesn't break out reason; conservative

        # Regime changes
        seen_regimes = [r["regime"] for r in wd.regime_history if r.get("regime")]
        regime_changes = sum(
            1 for i in range(1, len(seen_regimes)) if seen_regimes[i] != seen_regimes[i - 1]
        )
        current_regime = seen_regimes[-1] if seen_regimes else "UNKNOWN"

        # Criteria status
        trading_days = wd.week_num * 5  # approximate
        acc_3d       = acc.get("overall_accuracy_3d")
        win_rate     = wd.win_rate_pct
        max_dd       = wd.max_drawdown_pct

        def _status(ok: bool) -> str:
            return "PASS" if ok else "FAIL"

        acc_criterion      = _status(acc_3d is not None and acc_3d >= 55)
        drawdown_criterion = _status(max_dd <= 8)
        win_criterion      = _status(win_rate is not None and win_rate >= 45)
        regime_criterion   = _status(regime_changes <= 2)  # crude proxy

        weeks_remaining = max(0, (20 - trading_days) // 5)

        mf_scores = wd.mirofish_scores
        mf_min = min(mf_scores) if mf_scores else 0.0
        mf_max = max(mf_scores) if mf_scores else 0.0

        nepse_ret = wd.nepse_week_return_pct
        alpha = wd.alpha_pct

        return WEEKLY_REVIEW_PROMPT.format(
            week_num=wd.week_num,
            data_json=json.dumps(data_dict, indent=2, default=str)[:8000],  # token budget
            week_return_pct=wd.week_return_pct,
            nepse_return_pct=f"{nepse_ret:.2f}%" if nepse_ret is not None else "N/A",
            cumulative_return_pct=wd.cumulative_return_pct,
            alpha_pct=f"{alpha:+.2f}%" if alpha is not None else "N/A",
            acc_1d=_fmt_pct(acc.get("bull_accuracy_1d")),
            acc_3d=_fmt_pct(acc.get("overall_accuracy_3d")),
            acc_5d=_fmt_pct(acc.get("overall_accuracy_5d")),
            acc_last10=_fmt_pct(acc.get("last_10_signals_accuracy")),
            acc_trend=acc.get("accuracy_trend", "unknown"),
            acc_watchlist_5d=_fmt_pct(acc.get("watchlist_accuracy_5d")),
            mf_score_min=round(mf_min, 3),
            mf_score_max=round(mf_max, 3),
            stops_hit=stops_hit,
            targets_hit=targets_hit,
            max_drawdown_pct=max_dd,
            cash_utilisation_pct=wd.cash_utilisation_pct,
            current_regime=current_regime,
            regime_changes=regime_changes,
            trading_days_elapsed=trading_days,
            acc_criterion_status=acc_criterion,
            drawdown_criterion_status=drawdown_criterion,
            win_rate_criterion_status=win_criterion,
            regime_criterion_status=regime_criterion,
            weeks_to_live=weeks_remaining,
        )

    # ── Template fallback ────────────────────────────────────────────────────

    def _generate_template_report(self, wd: WeekData) -> str:
        """Generate a structured template report without LLM."""
        acc = wd.accuracy_report

        def _pct(v: Optional[float], default: str = "N/A") -> str:
            return f"{v:.1f}%" if v is not None else default

        nepse_ret = wd.nepse_week_return_pct
        alpha     = wd.alpha_pct

        # Best and worst trades
        sorted_trades = sorted(wd.closed_trades, key=lambda t: t.get("pnl_pct", 0), reverse=True)
        best_3  = sorted_trades[:3]
        worst_3 = sorted_trades[-3:] if len(sorted_trades) >= 3 else sorted_trades

        def _trade_row(t: dict) -> str:
            return (
                f"- **{t.get('symbol', '?')}**: "
                f"Entry NPR {t.get('entry_price', 0):,.0f} → "
                f"Exit NPR {t.get('exit_price', 0):,.0f} | "
                f"P&L: **{t.get('pnl_pct', 0):+.2f}%** | "
                f"Regime: {t.get('regime', '?')}"
            )

        # Current regime
        seen = [r["regime"] for r in wd.regime_history if r.get("regime")]
        current_regime = seen[-1] if seen else "UNKNOWN"
        regime_changes = sum(1 for i in range(1, len(seen)) if seen[i] != seen[i - 1])

        trading_days   = wd.week_num * 5
        max_dd         = wd.max_drawdown_pct
        acc_3d_val     = acc.get("overall_accuracy_3d")
        win_rate       = wd.win_rate_pct

        def _status(ok: bool) -> str:
            return "✅ PASS" if ok else "❌ FAIL"

        header = self._build_report_header(wd)

        lines = [
            header,
            "",
            "---",
            "",
            "### 1. Executive Summary",
            "",
            f"Week {wd.week_num} of paper trading produced a portfolio return of "
            f"**{wd.week_return_pct:+.2f}%** "
            f"(NEPSE: {f'{nepse_ret:+.2f}%' if nepse_ret is not None else 'N/A'}, "
            f"alpha: {f'{alpha:+.2f}%' if alpha is not None else 'N/A'}). "
            f"Current regime: **{current_regime}**. "
            f"Signal accuracy (3d): {_pct(acc_3d_val)}. "
            f"Portfolio at NPR {wd.portfolio_value_end:,.0f} "
            f"({wd.cumulative_return_pct:+.2f}% cumulative).",
            "",
            "---",
            "",
            "### 2. Performance vs NEPSE Index",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Week return | **{wd.week_return_pct:+.2f}%** |",
            f"| NEPSE week return | {f'{nepse_ret:+.2f}%' if nepse_ret is not None else 'N/A'} |",
            f"| Alpha | {f'{alpha:+.2f}%' if alpha is not None else 'N/A'} |",
            f"| Cumulative return | {wd.cumulative_return_pct:+.2f}% |",
            f"| Starting capital | NPR {wd.starting_capital:,.0f} |",
            f"| Current value | NPR {wd.portfolio_value_end:,.0f} |",
            "",
            "---",
            "",
            "### 3. Best Trades (Top 3)",
            "",
        ]

        if best_3:
            for t in best_3:
                lines.append(_trade_row(t))
        else:
            lines.append("_No closed trades this week._")

        lines += [
            "",
            "---",
            "",
            "### 4. Worst Trades (Top 3)",
            "",
        ]

        if worst_3:
            for t in worst_3:
                lines.append(_trade_row(t))
        else:
            lines.append("_No closed trades this week._")

        lines += [
            "",
            "---",
            "",
            "### 5. Signal Accuracy Analysis",
            "",
            f"| Window | Accuracy |",
            f"|--------|----------|",
            f"| 1-day (bull) | {_pct(acc.get('bull_accuracy_1d'))} |",
            f"| 3-day overall | {_pct(acc.get('overall_accuracy_3d'))} |",
            f"| 5-day overall | {_pct(acc.get('overall_accuracy_5d'))} |",
            f"| Last 10 signals | {_pct(acc.get('last_10_signals_accuracy'))} |",
            f"| Watchlist (5d) | {_pct(acc.get('watchlist_accuracy_5d'))} |",
            "",
            f"Trend: **{acc.get('accuracy_trend', 'unknown').upper()}**",
            f"Total signals evaluated: {acc.get('total_signals_evaluated', 0)}",
            "",
            "---",
            "",
            "### 6. MiroFish Quality Assessment",
            "",
        ]

        if wd.mirofish_scores:
            mf_min = min(wd.mirofish_scores)
            mf_max = max(wd.mirofish_scores)
            mf_avg = sum(wd.mirofish_scores) / len(wd.mirofish_scores)
            lines += [
                f"- Score range this week: **{mf_min:+.3f}** to **{mf_max:+.3f}**",
                f"- Average score: **{mf_avg:+.3f}**",
                f"- Observations: {len(wd.mirofish_scores)} sessions scored",
            ]
        else:
            lines.append("_No MiroFish scores available for this period._")

        lines += [
            "",
            "---",
            "",
            "### 7. Risk Management Assessment",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Max intra-week drawdown | {max_dd:.2f}% |",
            f"| Cash utilisation | {wd.cash_utilisation_pct:.1f}% |",
            f"| Open positions | {len(wd.open_positions)} |",
            f"| Closed trades this week | {len(wd.closed_trades)} |",
            f"| Win rate | {_pct(win_rate)} |",
            "",
            "---",
            "",
            "### 8. Market Regime Assessment",
            "",
            f"- Current regime: **{current_regime}**",
            f"- Regime changes this week: {regime_changes}",
            f"- Regime history: {', '.join(seen[-5:]) if seen else 'N/A'}",
            "",
            "---",
            "",
            "### 9. Strategy Adjustments for Next Week",
            "",
            "1. **Review signal accuracy thresholds** — if 3d accuracy < 55%, reduce MiroFish signal weight by 10%.",
            "2. **Tighten stop-losses in BEAR regime** — use 7% stop instead of 8% until regime confirms recovery.",
            "3. **Increase cash reserve if regime = SIDEWAYS** — cap deployment at 60% of portfolio.",
            "4. **Review watchlist tier criteria** — promote Tier B stocks to A only if volume > 2× 20d average.",
            "5. **Monitor NST schedule** — verify daily cycle is running at 15:30 NST without gaps.",
            "",
            "---",
            "",
            "### 10. Go-Live Progress",
            "",
            f"| Criterion | Status |",
            f"|-----------|--------|",
            f"| Trading days completed ({trading_days}/20) | {'✅ DONE' if trading_days >= 20 else f'⏳ {20 - trading_days} remaining'} |",
            f"| Signal accuracy ≥55% (3d) | {_status(acc_3d_val is not None and acc_3d_val >= 55)} |",
            f"| Max drawdown ≤8% | {_status(max_dd <= 8)} |",
            f"| Win rate ≥45% | {_status(win_rate is not None and win_rate >= 45)} |",
            f"| Regime detection ≥3 correct | {_status(regime_changes <= 2)} |",
            "",
            f"**Overall assessment**: {'READY FOR REVIEW' if trading_days >= 20 else 'ON_TRACK' if max_dd <= 8 else 'NOT_READY'}",
            "",
            "---",
            "",
            f"_Report generated: {_nst_now().strftime('%Y-%m-%d %H:%M NST')} (template mode — no ANTHROPIC_API_KEY)_",
        ]

        return "\n".join(lines)

    # ── Helpers ──────────────────────────────────────────────────────────────

    def _build_report_header(self, wd: WeekData) -> str:
        return (
            f"# MiroFish Paper Trading — Weekly Review\n"
            f"## Week {wd.week_num}: {wd.week_start} → {wd.week_end}\n"
            f"**Session**: `{wd.session_id}`  "
            f"**Generated**: {_nst_now().strftime('%Y-%m-%d %H:%M NST')}"
        )

    def _wd_to_dict(self, wd: WeekData) -> dict:
        """Serialise WeekData to a JSON-safe dict for the prompt."""
        return {
            "session_id":              wd.session_id,
            "week_num":                wd.week_num,
            "week_start":              str(wd.week_start),
            "week_end":                str(wd.week_end),
            "portfolio_value_start":   round(wd.portfolio_value_start, 2),
            "portfolio_value_end":     round(wd.portfolio_value_end, 2),
            "starting_capital":        round(wd.starting_capital, 2),
            "cash_end":                round(wd.cash_end, 2),
            "week_return_pct":         round(wd.week_return_pct, 3),
            "cumulative_return_pct":   round(wd.cumulative_return_pct, 3),
            "nepse_week_return_pct":   wd.nepse_week_return_pct,
            "alpha_pct":               wd.alpha_pct,
            "max_drawdown_pct":        wd.max_drawdown_pct,
            "cash_utilisation_pct":    wd.cash_utilisation_pct,
            "win_rate_pct":            wd.win_rate_pct,
            "closed_trades":           wd.closed_trades,
            "open_positions_count":    len(wd.open_positions),
            "regime_history":          wd.regime_history[-7:],
            "mirofish_scores":         wd.mirofish_scores[-7:],
            "accuracy_report":         wd.accuracy_report,
            "cycle_logs_count":        len(wd.cycle_logs),
        }

    def _compute_week_num(self) -> int:
        """Derive the current week number from the session's first snapshot."""
        pattern = str(self._base / "snapshot_*.json")
        files = sorted(glob.glob(pattern))
        if not files:
            return 1
        try:
            with open(files[0], encoding="utf-8") as fh:
                first_snap = json.load(fh)
            first_date_str = first_snap.get("date") or str(date.today())
            first_date = date.fromisoformat(str(first_date_str))
            delta_days = (date.today() - first_date).days
            return max(1, (delta_days // 7) + 1)
        except Exception:
            return 1

    def _extract_telegram_summary(self, content: str, week_num: int) -> str:
        """Extract a short Telegram summary from the report."""
        lines = content.split("\n")
        summary_lines: list[str] = []
        in_exec = False
        for line in lines:
            if "### 1. Executive Summary" in line:
                in_exec = True
                continue
            if in_exec:
                if line.startswith("###") or line.startswith("---"):
                    break
                if line.strip():
                    summary_lines.append(line.strip())

        exec_text = " ".join(summary_lines)[:400] if summary_lines else "See attached report."

        return (
            f"📋 *MiroFish Weekly Review — Week {week_num}*\n\n"
            f"{exec_text}\n\n"
            f"_Full report saved to_ `data/processed/paper_trading/weekly_review_week{week_num}.md`"
        )

    def _send_telegram(self, message: str) -> bool:
        """Send message via telegram_bot utility."""
        try:
            from paper_trading.telegram_bot import _load_latest_engine_state  # noqa: F401 — confirms import
            import urllib.request
            bot_token = os.environ.get("TELEGRAM_BOT_TOKEN", "")
            chat_id   = os.environ.get("TELEGRAM_CHAT_ID", "")
            if not bot_token or not chat_id or "your_" in bot_token:
                logger.debug("Telegram not configured — skipping weekly review send")
                return False
            url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
            payload = json.dumps({
                "chat_id":    chat_id,
                "text":       message,
                "parse_mode": "Markdown",
            }).encode("utf-8")
            req = urllib.request.Request(
                url, data=payload, headers={"Content-Type": "application/json"}
            )
            with urllib.request.urlopen(req, timeout=15) as resp:
                return resp.status == 200
        except Exception as exc:
            logger.warning("Telegram send failed: %s", exc)
            return False


# ---------------------------------------------------------------------------
# APScheduler integration — Friday 12:15 UTC (18:00 NST)
# ---------------------------------------------------------------------------

def schedule_weekly_review(session_id: Optional[str] = None, data_dir: str = "data/paper_trading") -> None:
    """
    Start APScheduler with a cron trigger: every Friday at 12:15 UTC (18:00 NST).
    Blocks until Ctrl+C.
    """
    try:
        from apscheduler.schedulers.blocking import BlockingScheduler
        from apscheduler.triggers.cron import CronTrigger
    except ImportError:
        logger.error("apscheduler not installed — run: pip install apscheduler")
        raise SystemExit(1)

    def _resolve_session() -> str:
        if session_id:
            return session_id
        active_file = Path(data_dir) / "active_session.txt"
        if active_file.exists():
            return active_file.read_text(encoding="utf-8").strip()
        dirs = sorted(
            [d for d in Path(data_dir).iterdir() if d.is_dir()],
            key=lambda d: d.stat().st_mtime,
            reverse=True,
        )
        return dirs[0].name if dirs else f"paper_{date.today()}"

    def _run_review():
        sid = _resolve_session()
        reviewer = WeeklyReviewer(session_id=sid, data_dir=data_dir)
        result = reviewer.run_weekly_review()
        logger.info("Scheduled weekly review complete: %s", result)

    scheduler = BlockingScheduler(timezone="UTC")
    scheduler.add_job(
        _run_review,
        CronTrigger(day_of_week="fri", hour=12, minute=15),
        id="weekly_review",
        name="MiroFish weekly review (Friday 18:00 NST)",
        misfire_grace_time=3600,  # fire up to 1h late if scheduler was down
    )

    logger.info("Weekly review scheduler started. Fires every Friday 12:15 UTC (18:00 NST).")
    print("\n  MiroFish weekly review scheduler running.")
    print("  Fires: Every Friday at 12:15 UTC (18:00 NST)")
    print("  Press Ctrl+C to stop.\n")
    scheduler.start()


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> None:
    import argparse

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s  %(levelname)-7s  %(message)s",
        datefmt="%H:%M:%S",
    )

    parser = argparse.ArgumentParser(
        description="MiroFish automated weekly review",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--run-now", action="store_true",
        help="Generate and save the weekly review immediately, then exit",
    )
    parser.add_argument(
        "--week-num", type=int, default=None,
        help="Override week number (default: auto-derived from session start date)",
    )
    parser.add_argument(
        "--session-id", default=None,
        help="Paper trading session ID (default: reads active_session.txt)",
    )
    parser.add_argument(
        "--data-dir", default="data/paper_trading",
        help="Path to paper trading data root",
    )
    args = parser.parse_args()

    # Resolve session
    session_id = args.session_id
    if not session_id:
        active_file = Path(args.data_dir) / "active_session.txt"
        if active_file.exists():
            session_id = active_file.read_text(encoding="utf-8").strip()
        else:
            dirs = sorted(
                [d for d in Path(args.data_dir).iterdir() if d.is_dir()],
                key=lambda d: d.stat().st_mtime,
                reverse=True,
            ) if Path(args.data_dir).exists() else []
            session_id = dirs[0].name if dirs else f"paper_{date.today()}"

    logger.info("Session: %s | Data dir: %s", session_id, args.data_dir)

    reviewer = WeeklyReviewer(session_id=session_id, data_dir=args.data_dir)

    if args.run_now:
        week_num = args.week_num or reviewer._compute_week_num()
        content  = reviewer.generate_review(week_num)
        out_path = reviewer.save_review(content, week_num)
        print(f"\nWeekly review written to: {out_path}")
        print(f"Characters: {len(content):,}")
        print("\n--- Preview (first 500 chars) ---")
        print(content[:500])
    else:
        schedule_weekly_review(session_id=session_id, data_dir=args.data_dir)


if __name__ == "__main__":
    main()
